# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wyrm < Formula
  desc "Repeatable tmux session layouts from a TOML config"
  homepage "https://github.com/jskoll/wyrm"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.6/wyrm_0.1.6_darwin_amd64.tar.gz"
      sha256 "d5edb97284261e8fb86dc4e6b60354c88f5b01bb96cd9775bed88377bf684928"

      define_method(:install) do
        bin.install "wyrm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.6/wyrm_0.1.6_darwin_arm64.tar.gz"
      sha256 "6d7feed25b9d0c22ed143d25e80a5771672058e53c671496f4c7e8640188e591"

      define_method(:install) do
        bin.install "wyrm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.6/wyrm_0.1.6_linux_amd64.tar.gz"
      sha256 "0caf44997f2fa07ee4680cf080c5781c01db6f63e34ba4d6232f06f998f5166d"
      define_method(:install) do
        bin.install "wyrm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.6/wyrm_0.1.6_linux_arm64.tar.gz"
      sha256 "3d51f91f3ddf0c6734a238e433d32db86b61788a490a3a538dbf903bdad094de"
      define_method(:install) do
        bin.install "wyrm"
      end
    end
  end
end
