# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wyrm < Formula
  desc "Repeatable tmux session layouts from a TOML config"
  homepage "https://github.com/jskoll/wyrm"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.7/wyrm_0.1.7_darwin_amd64.tar.gz"
      sha256 "9d65040839654d181fc6d482fbf3e5d8c2c3dec9eaaa4ab7b6af7150d3be9cb8"

      define_method(:install) do
        bin.install "wyrm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.7/wyrm_0.1.7_darwin_arm64.tar.gz"
      sha256 "93bf156e3fd5886e61ee0516e242a073095ee63776f5eab644de760e6086975c"

      define_method(:install) do
        bin.install "wyrm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.7/wyrm_0.1.7_linux_amd64.tar.gz"
      sha256 "6a7d707f28a0f8d1df5e069f5952699c1af2db5bf79e64b582c90d64a5cbe302"
      define_method(:install) do
        bin.install "wyrm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jskoll/wyrm/releases/download/v0.1.7/wyrm_0.1.7_linux_arm64.tar.gz"
      sha256 "43bd7aefea36889efb4cfe3683b49d3372184e6c9f9a10ea456d1c955e85bee2"
      define_method(:install) do
        bin.install "wyrm"
      end
    end
  end
end
